### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by githicham** [facebookresearch/vocoder-benchmark#8]
Hi,

In your paper, you train and compare different models on various metrics.
Are you planning on releasing the model weights you obtained as pretrained models? 

Regards,

**Comment by ebadawy** [comment]
Not sure if we will share the pre-trained models (at least at the moment); However, we have shared the config files that are used to train each model. Hopefully, this will make it easier to reproduce the results in the paper.

**Comment by githicham** [comment]
I started training a DiffWave model on the LJSpeech dataset with a single GPU (using your config file), just to estimate the time it would take. That's what pushed me to ask about pretrained models :-)
I am closing the issue since the initial question has been answered.

**Comment by ebadawy** [comment]
I would suggest to keep the issue open in case someone would be interested to train and share their pre-trained models. Will try to do so later on once I get the chance.
